# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-24 22:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('picture', models.ImageField(help_text='Max 200px X 200px', upload_to='funcionarios/fotos')),
                ('telefono', models.CharField(blank=True, max_length=200, null=True)),
                ('extension', models.CharField(blank=True, max_length=10, null=True)),
                ('id_puesto', models.CharField(blank=True, max_length=200, null=True)),
                ('unidad', models.CharField(blank=True, max_length=200, null=True)),
                ('nombre_superior', models.CharField(blank=True, max_length=200, null=True)),
                ('sueldo_base', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('compensacion_garantizada', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('total_bruto', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('total_neto', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('currency', models.CharField(blank=True, default='MXN', max_length=3, null=True)),
                ('seguro_institucional', models.CharField(blank=True, max_length=200, null=True)),
                ('seguro_colectivo_retiro', models.CharField(blank=True, max_length=200, null=True)),
                ('seguro_gastos_medicos', models.CharField(blank=True, max_length=200, null=True)),
                ('seguro_separacion_individualizado', models.CharField(blank=True, max_length=200, null=True)),
                ('prima_vacacional', models.CharField(blank=True, max_length=200, null=True)),
                ('prima_antiguedad', models.CharField(blank=True, max_length=200, null=True)),
                ('gratificacion_fin_ano', models.CharField(blank=True, max_length=200, null=True)),
                ('pagas_defuncion', models.CharField(blank=True, max_length=200, null=True)),
                ('ayuda_despensa', models.CharField(blank=True, max_length=200, null=True)),
                ('vacaciones', models.CharField(blank=True, max_length=200, null=True)),
                ('ISSSTE', models.CharField(blank=True, max_length=200, null=True)),
                ('FOVISSSTE', models.CharField(blank=True, max_length=200, null=True)),
                ('SAR', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='funcionario',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.Institucion'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='funcionarios.Tag'),
        ),
    ]
