# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-24 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='last_name',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='apellido_materno',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='apellido_paterno',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='nombre',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='picture',
            field=models.ImageField(blank=True, help_text='Max 200px X 200px', null=True, upload_to='funcionarios/fotos'),
        ),
    ]
